# Generated by Django 6.0.1 on 2026-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('ite_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_quantity', models.IntegerField()),
            ],
        ),
    ]
