# Generated by Django 6.0.1 on 2026-02-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ite_price',
            new_name='item_price',
        ),
    ]
